apiVersion: extensions/v1beta1
kind: Deployment
metadata:
        name: webapp-deployment
        labels:
                app: webapp
spec:
        replicas: 1
        selector:
                matchLabels: 
                        app: webapp
        template:
                metadata:
                        labels:
                                app: webapp
                spec:
                        containers:
                        - name: webapp
                          image: alextanhongpin/python:latest
                          imagePullPolicy: Never
                          ports:
                          - containerPort: 8000

