---
apiVersion: v1
kind: Service
metadata:
  name: webservice
spec:
  # Using Docker Desktop, NodePort is required to expose the endpoint.
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
